---

- name: Deploy Trafsys Data Transfer
  hosts: uda4
  remote_user: ulsprovision
  vars:
    app_folder: /var/opt/trafsys-data-transfer
    user: trafsysdatatransfer

  tasks:
    - name: Grab env vars from env_vars.yml
      include_vars:
        file: env_vars.yml
        name: env_vars

    - name: Clone from git
      git:
        repo: https://github.com/ulsdevteam/trafsys-data-transfer.git
        dest: '{{ app_folder }}'
        force: yes
      become: yes

    - name: Create dedicated user
      user:
        name: '{{ user }}'
        state: present
      become: yes

    - name: Set group permissions
      file:
        path: '{{ app_folder }}'
        state: directory
        recurse: yes
        group: ulssysdev
        owner: '{{ user }}'
        mode: '02770'
      become: yes

    - name: Set environment variables
      lineinfile:
        dest: '/home/{{ user }}/.profile'
        state: present
        regexp: '^export {{ item.key }}='
        line: 'export {{ item.key }}={{ item.value }}'
      with_items: '{{ env_vars | dict2items }}'
      become: yes

    - name: enable source
      lineinfile:
        dest: '/home/{{ user }}/.profile'
        state: present
        line: 'source scl_source enable rh-nodejs14'
      become: yes

    - name: Install node dependencies
      community.general.npm:
        path: '{{ app_folder }}'
      become: yes
      become_user: '{{ user }}'
      become_flags: '-i'

    - name: Schedule cron job
      cron:
        name: 'run trafsys-data-transfer'
        hour: '5'
        minute: '0'
        job: "/usr/local/bin/cronic sh -c 'source ~/.profile; node /var/opt/trafsys-data-transfer/script.js'"
      become: yes
      become_user: '{{ user }}'

    - name: Send mail to root
      lineinfile:
        dest: /etc/aliases
        regexp: '^trafsysdatatransfer:'
        line: 'trafsysdatatransfer: root'
      become: yes